name: Deploy OpenGol Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Chequear Vars y Red
      run: |
        echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
        ping -c 3 ${{ secrets.SERVER_HOST }} || echo "No responde a ping"
        nc -vz ${{ secrets.SERVER_HOST }} 22 || echo "Puerto 22 no disponible"
    - name: Check server connectivity
      run: nslookup ${{ secrets.SERVER_HOST }} && ping -c 4 ${{ secrets.SERVER_HOST }}
    - name: Deploy to Oracle server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 143.47.44.40
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          set -e
          cd ~/OpenGol-Backend
          git pull origin main
          docker compose up -d --build
          docker image prune -f